import Link from 'next/link'
import { ArrowLeft, CalendarDays, Check, CircleUserRound, Link2, Trash2 } from 'lucide-react'
import { notFound } from 'next/navigation'
import type { Client, Lead, User } from '@/payload-types'
import { getTaskDetail, TASK_PRIORITIES, TASK_STATUSES } from '@/lib/tasks-data'
import { getWorkspaceContext } from '@/lib/workspace-context'
import { deleteTaskAction, toggleChecklistAction, updateTaskAction } from '../actions'

const labels = { pendiente: 'Pendiente', en_progreso: 'En progreso', bloqueada: 'Bloqueada', completada: 'Completada', cancelada: 'Cancelada', baja: 'Baja', media: 'Media', alta: 'Alta', urgente: 'Urgente' }
const relId = (value: number | { id: number } | null | undefined) => typeof value === 'number' ? value : value?.id
const person = (user: number | User | null | undefined) => user && typeof user === 'object' ? `${user.firstName ?? ''} ${user.lastName ?? ''}`.trim() || user.email : 'Sin asignar'

export default async function TaskDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; updated?: string }> }) {
  const [{ id }, notice, context] = await Promise.all([params, searchParams, getWorkspaceContext()])
  const taskId = Number(id); if (!Number.isInteger(taskId)) notFound()
  const [task, assignees, clients, leads] = await Promise.all([
    getTaskDetail({ payload: context.payload, user: context.user, tenantId: context.tenantId, id: taskId }),
    context.payload.find({ collection: 'users', limit: 100, overrideAccess: false, user: context.user, where: { 'tenants.tenant': { equals: context.tenantId } } }),
    context.payload.find({ collection: 'clients', limit: 100, overrideAccess: false, user: context.user, where: { tenant: { equals: context.tenantId } } }),
    context.payload.find({ collection: 'leads', limit: 100, overrideAccess: false, user: context.user, where: { tenant: { equals: context.tenantId } } }),
  ])
  if (!task) notFound()
  return <div className="workspace-page task-detail-page">
    <Link className="tasks-back" href="/tasks"><ArrowLeft size={16}/>Volver a tareas</Link>
    {(notice.created || notice.updated) && <div className="tasks-success"><Check size={17}/>{notice.created ? 'Tarea creada correctamente.' : 'Cambios guardados.'}</div>}
    <header className="task-detail-head"><div><span className={`tasks-priority tasks-priority-${task.priority}`}>{labels[task.priority]}</span><h1>{task.title}</h1><p>Tarea #{task.id} · Actualizada {new Intl.DateTimeFormat('es', { dateStyle: 'medium' }).format(new Date(task.updatedAt))}</p></div>{context.isAdmin && <form action={deleteTaskAction}><input type="hidden" name="id" value={task.id}/><button className="workspace-button tasks-danger" type="submit"><Trash2 size={15}/>Eliminar</button></form>}</header>
    {!context.canEdit && <div className="tasks-readonly"><CircleUserRound size={18}/><div><strong>Vista de solo lectura</strong><span>Puedes revisar todos los detalles de esta tarea.</span></div></div>}
    <div className="task-detail-grid"><section className="workspace-card task-detail-main">{context.canEdit ? <form action={updateTaskAction} className="tasks-form"><input type="hidden" name="id" value={task.id}/><label>Título<input name="title" defaultValue={task.title} required/></label><label>Descripción<textarea name="description" rows={6} defaultValue={task.description ?? ''}/></label><div className="tasks-form-grid"><label>Estado<select name="status" defaultValue={task.status}>{TASK_STATUSES.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></label><label>Prioridad<select name="priority" defaultValue={task.priority}>{TASK_PRIORITIES.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></label><label>Fecha límite<input name="dueDate" type="date" defaultValue={task.dueDate?.slice(0,10) ?? ''}/></label><label>Responsable<select name="assignedTo" defaultValue={relId(task.assignedTo)}><option value="">Sin asignar</option>{assignees.docs.map((item) => { const user = item as User; return <option key={user.id} value={user.id}>{person(user)}</option> })}</select></label><label>Cliente<select name="client" defaultValue={relId(task.client)}><option value="">Ninguno</option>{clients.docs.map((item) => { const client = item as Client; return <option key={client.id} value={client.id}>{client.name}</option> })}</select></label><label>Lead<select name="lead" defaultValue={relId(task.lead)}><option value="">Ninguno</option>{leads.docs.map((item) => { const lead = item as Lead; return <option key={lead.id} value={lead.id}>{lead.fullName}</option> })}</select></label></div><label>Checklist <small>Una subtarea por línea</small><textarea name="checklist" rows={5} defaultValue={(task.checklist ?? []).map((item) => item.item).join('\n')}/></label><button className="workspace-button workspace-button-primary" type="submit">Guardar cambios</button></form> : <div className="task-readonly-copy"><h2>Descripción</h2><p>{task.description || 'Sin descripción.'}</p></div>}</section>
    <aside className="workspace-stack"><section className="workspace-card task-meta"><h2>Contexto</h2><dl><div><dt><CalendarDays size={15}/>Vencimiento</dt><dd>{task.dueDate ? new Intl.DateTimeFormat('es', { dateStyle: 'long' }).format(new Date(task.dueDate)) : 'Sin fecha'}</dd></div><div><dt><CircleUserRound size={15}/>Responsable</dt><dd>{person(task.assignedTo)}</dd></div><div><dt><Link2 size={15}/>Relación CRM</dt><dd>{task.client && typeof task.client === 'object' ? <Link href={`/crm/clientes/${task.client.id}`}>{task.client.name}</Link> : task.lead && typeof task.lead === 'object' ? <Link href={`/crm/leads/${task.lead.id}`}>{task.lead.fullName}</Link> : 'Sin relación'}</dd></div></dl></section><section className="workspace-card task-checklist"><h2>Checklist</h2>{task.checklist?.length ? <div>{task.checklist.map((item, index) => <form action={toggleChecklistAction} key={item.id ?? item.item}><input type="hidden" name="id" value={task.id}/><input type="hidden" name="index" value={index}/><button type="submit" disabled={!context.canEdit} data-done={Boolean(item.done)}><span>{item.done ? <Check size={14}/> : null}</span>{item.item}</button></form>)}</div> : <p>Sin subtareas.</p>}</section></aside></div>
  </div>
}
