import Link from 'next/link'
import { CheckCircle2, CircleAlert, Clock3, ListFilter, Plus, Search, UserRound } from 'lucide-react'
import type { Client, Lead, Task, User } from '@/payload-types'
import { checklistProgress, dueState, TASK_PRIORITIES, TASK_STATUSES, type TaskFilters, type TaskStatus } from '@/lib/tasks-filters'
import { changeTaskStatusAction, createTaskAction } from '../actions'

const statusLabel: Record<TaskStatus, string> = { pendiente: 'Pendiente', en_progreso: 'En progreso', bloqueada: 'Bloqueada', completada: 'Completada', cancelada: 'Cancelada' }
const priorityLabel = { baja: 'Baja', media: 'Media', alta: 'Alta', urgente: 'Urgente' }
const person = (user: number | User | null | undefined) => user && typeof user === 'object' ? `${user.firstName ?? ''} ${user.lastName ?? ''}`.trim() || user.email : 'Sin asignar'
const relation = (task: Task) => task.client && typeof task.client === 'object' ? task.client.name : task.lead && typeof task.lead === 'object' ? task.lead.fullName : 'Sin relación CRM'
const dateLabel = (value?: string | null) => value ? new Intl.DateTimeFormat('es', { day: '2-digit', month: 'short' }).format(new Date(value)) : 'Sin fecha'

function TaskCard({ task, canEdit }: { task: Task; canEdit: boolean }) {
  const progress = checklistProgress(task.checklist)
  const due = dueState(task.dueDate)
  return <article className="tasks-card">
    <div className="tasks-card-top"><span className={`tasks-priority tasks-priority-${task.priority}`}>{priorityLabel[task.priority]}</span><span className={`tasks-due tasks-due-${due}`}><Clock3 size={13}/>{dateLabel(task.dueDate)}</span></div>
    <Link href={`/tasks/${task.id}`} className="tasks-card-title">{task.title}</Link>
    <p className="tasks-card-relation">{relation(task)}</p>
    {progress.total > 0 && <div className="tasks-progress"><div><span>{progress.done}/{progress.total} subtareas</span><span>{progress.percent}%</span></div><progress max="100" value={progress.percent}/></div>}
    <div className="tasks-card-footer"><span className="tasks-assignee"><UserRound size={14}/>{person(task.assignedTo)}</span>{canEdit && <form action={changeTaskStatusAction}><input type="hidden" name="id" value={task.id}/><select name="status" defaultValue={task.status} aria-label={`Cambiar estado de ${task.title}`} onChange={(event) => event.currentTarget.form?.requestSubmit()}>{TASK_STATUSES.map((status) => <option key={status} value={status}>{statusLabel[status]}</option>)}</select></form>}</div>
  </article>
}

export function TasksWorkspace({ data, filters, canEdit }: { data: { tasks: Task[]; columns: { status: TaskStatus; total: number; tasks: Task[] }[]; metrics: { pending: number; inProgress: number; overdue: number; completedWeek: number }; assignees: User[]; clients: Client[]; leads: Lead[]; pagination: { page: number; totalPages: number; hasPrevPage: boolean; hasNextPage: boolean } }; filters: TaskFilters; canEdit: boolean }) {
  return <div className="workspace-page tasks-page">
    <header className="workspace-page-head"><div><div className="workspace-eyebrow"><span className="workspace-eyebrow-dot"/>OPERACIONES / TAREAS</div><h1 className="workspace-title">Trabajo del equipo</h1><p className="workspace-subtitle">Prioriza, asigna y mueve el trabajo sin perder contexto del cliente.</p></div>{canEdit && <details className="tasks-create"><summary className="workspace-button workspace-button-primary"><Plus size={16}/>Nueva tarea</summary><div className="tasks-create-panel"><div><strong>Nueva tarea</strong><span>Define el resultado y quién lo llevará.</span></div><TaskForm assignees={data.assignees} clients={data.clients} leads={data.leads}/></div></details>}</header>
    {!canEdit && <div className="tasks-readonly"><CircleAlert size={18}/><div><strong>Vista de solo lectura</strong><span>Tu rol permite consultar el trabajo, pero no modificarlo.</span></div></div>}
    <section className="workspace-kpis tasks-metrics" aria-label="Resumen de tareas">{[[data.metrics.pending,'Pendientes','Por iniciar'],[data.metrics.inProgress,'En progreso','Trabajo activo'],[data.metrics.overdue,'Vencidas','Necesitan atención'],[data.metrics.completedWeek,'Completadas','Últimos 7 días']].map(([value,label,note]) => <article className="workspace-card workspace-kpi" key={String(label)}><div className="workspace-kpi-top"><span className="workspace-kpi-label">{label}</span>{label === 'Vencidas' ? <CircleAlert size={18}/> : <CheckCircle2 size={18}/>}</div><div className="workspace-kpi-value">{value}</div><div className="workspace-kpi-note">{note}</div></article>)}</section>
    <form className="tasks-toolbar"><div className="tasks-view-switch"><Link data-active={filters.view === 'tablero'} href="/tasks?vista=tablero">Tablero</Link><Link data-active={filters.view === 'lista'} href="/tasks?vista=lista">Lista</Link></div><label className="tasks-search"><Search size={16}/><span className="sr-only">Buscar tareas</span><input name="q" defaultValue={filters.query} placeholder="Buscar tareas..."/></label><select name="estado" defaultValue={filters.status}><option value="todos">Todos los estados</option>{TASK_STATUSES.map((status) => <option key={status} value={status}>{statusLabel[status]}</option>)}</select><select name="prioridad" defaultValue={filters.priority}><option value="todas">Todas las prioridades</option>{TASK_PRIORITIES.map((priority) => <option key={priority} value={priority}>{priorityLabel[priority]}</option>)}</select><select name="responsable" defaultValue={filters.assignee}><option value="todos">Todo el equipo</option>{data.assignees.map((user) => <option key={user.id} value={user.id}>{person(user)}</option>)}</select><select name="vencimiento" defaultValue={filters.due}><option value="todos">Cualquier fecha</option><option value="vencidas">Vencidas</option><option value="hoy">Hoy</option><option value="semana">Próximos 7 días</option><option value="sin_fecha">Sin fecha</option></select><input type="hidden" name="vista" value={filters.view}/><button className="workspace-button" type="submit"><ListFilter size={15}/>Aplicar</button></form>
    {data.tasks.length === 0 ? <div className="tasks-empty"><CheckCircle2 size={32}/><h2>No hay tareas en esta vista</h2><p>Ajusta los filtros o crea la primera tarea para empezar.</p></div> : filters.view === 'tablero' ? <section className="tasks-board" aria-label="Tablero de tareas">{data.columns.map((column) => <section className="tasks-column" key={column.status}><header><span className={`tasks-status-dot tasks-status-${column.status}`}/><h2>{statusLabel[column.status]}</h2><span>{column.total}</span></header><div className="tasks-column-body">{column.tasks.length ? column.tasks.map((task) => <TaskCard key={task.id} task={task} canEdit={canEdit}/>) : <p className="tasks-column-empty">Sin tareas</p>}</div></section>)}</section> : <section className="workspace-card tasks-list"><div className="tasks-list-head"><span>Tarea</span><span>Estado</span><span>Prioridad</span><span>Responsable</span><span>Vencimiento</span></div>{data.tasks.map((task) => <Link href={`/tasks/${task.id}`} className="tasks-list-row" key={task.id}><span><strong>{task.title}</strong><small>{relation(task)}</small></span><span>{statusLabel[task.status]}</span><span className={`tasks-priority tasks-priority-${task.priority}`}>{priorityLabel[task.priority]}</span><span>{person(task.assignedTo)}</span><span className={`tasks-due-${dueState(task.dueDate)}`}>{dateLabel(task.dueDate)}</span></Link>)}</section>}
  </div>
}

function TaskForm({ assignees, clients, leads }: { assignees: User[]; clients: Client[]; leads: Lead[] }) { return <form action={createTaskAction} className="tasks-form"><label>Título<input name="title" required maxLength={180}/></label><label>Descripción<textarea name="description" rows={3}/></label><div className="tasks-form-grid"><label>Estado<select name="status" defaultValue="pendiente">{TASK_STATUSES.map((status) => <option key={status} value={status}>{statusLabel[status]}</option>)}</select></label><label>Prioridad<select name="priority" defaultValue="media">{TASK_PRIORITIES.map((priority) => <option key={priority} value={priority}>{priorityLabel[priority]}</option>)}</select></label><label>Fecha límite<input type="date" name="dueDate"/></label><label>Responsable<select name="assignedTo"><option value="">Sin asignar</option>{assignees.map((user) => <option key={user.id} value={user.id}>{person(user)}</option>)}</select></label><label>Cliente<select name="client"><option value="">Ninguno</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Lead<select name="lead"><option value="">Ninguno</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.fullName}</option>)}</select></label></div><label>Checklist <small>Una subtarea por línea</small><textarea name="checklist" rows={4}/></label><div className="tasks-form-actions"><button className="workspace-button workspace-button-primary" type="submit">Crear tarea</button></div></form> }
