/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    companies: Company;
    clients: Client;
    leads: Lead;
    activities: Activity;
    appointments: Appointment;
    segments: Segment;
    documents: Document;
    media: Media;
    'invoice-media': InvoiceMedia;
    payments: Payment;
    memberships: Membership;
    conversations: Conversation;
    messages: Message;
    'message-templates': MessageTemplate;
    notifications: Notification;
    'email-log': EmailLog;
    'email-messages': EmailMessage;
    'email-campaigns': EmailCampaign;
    offers: Offer;
    notes: Note;
    whiteboards: Whiteboard;
    'lead-briefs': LeadBrief;
    'form-submissions': FormSubmission;
    tasks: Task;
    'conversation-summaries': ConversationSummary;
    'conversation-notes': ConversationNote;
    'saved-crm-views': SavedCrmView;
    sequences: Sequence;
    'sequence-enrollments': SequenceEnrollment;
    'social-accounts': SocialAccount;
    'social-posts': SocialPost;
    'post-metrics': PostMetric;
    'company-settings': CompanySetting;
    'tenant-integrations': TenantIntegration;
    'tenant-connections': TenantConnection;
    exports: Export;
    imports: Import;
    invoices: Invoice;
    quotes: Quote;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    companies: {
      clients: 'clients';
    };
    clients: {
      activities: 'activities';
      conversations: 'conversations';
      tasks: 'tasks';
      payments: 'payments';
      memberships: 'memberships';
      documents: 'documents';
      formSubmissions: 'form-submissions';
      emailLog: 'email-log';
      emailMessages: 'email-messages';
      appointments: 'appointments';
    };
    leads: {
      touchpoints: 'activities';
      contenidoRelacionado: 'notes';
      tareas: 'tasks';
      tasks: 'tasks';
      conversations: 'conversations';
      formSubmissions: 'form-submissions';
      appointments: 'appointments';
    };
  };
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    segments: SegmentsSelect<false> | SegmentsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'invoice-media': InvoiceMediaSelect<false> | InvoiceMediaSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'message-templates': MessageTemplatesSelect<false> | MessageTemplatesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'email-log': EmailLogSelect<false> | EmailLogSelect<true>;
    'email-messages': EmailMessagesSelect<false> | EmailMessagesSelect<true>;
    'email-campaigns': EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    whiteboards: WhiteboardsSelect<false> | WhiteboardsSelect<true>;
    'lead-briefs': LeadBriefsSelect<false> | LeadBriefsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'conversation-summaries': ConversationSummariesSelect<false> | ConversationSummariesSelect<true>;
    'conversation-notes': ConversationNotesSelect<false> | ConversationNotesSelect<true>;
    'saved-crm-views': SavedCrmViewsSelect<false> | SavedCrmViewsSelect<true>;
    sequences: SequencesSelect<false> | SequencesSelect<true>;
    'sequence-enrollments': SequenceEnrollmentsSelect<false> | SequenceEnrollmentsSelect<true>;
    'social-accounts': SocialAccountsSelect<false> | SocialAccountsSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'post-metrics': PostMetricsSelect<false> | PostMetricsSelect<true>;
    'company-settings': CompanySettingsSelect<false> | CompanySettingsSelect<true>;
    'tenant-integrations': TenantIntegrationsSelect<false> | TenantIntegrationsSelect<true>;
    'tenant-connections': TenantConnectionsSelect<false> | TenantConnectionsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'shop-info': ShopInfo;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'shop-info': ShopInfoSelect<false> | ShopInfoSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      'payment-reminders': TaskPaymentReminders;
      'daily-digest': TaskDailyDigest;
      'sync-templates': TaskSyncTemplates;
      'openbsp-error-poll': TaskOpenbspErrorPoll;
      'send-campaign-batch': TaskSendCampaignBatch;
      'send-scheduled-campaigns': TaskSendScheduledCampaigns;
      'sync-email': TaskSyncEmail;
      'sync-gcal': TaskSyncGcal;
      'generate-lead-brief': TaskGenerateLeadBrief;
      'summarize-conversation': TaskSummarizeConversation;
      'sweep-unsummarized-conversations': TaskSweepUnsummarizedConversations;
      'recalculate-lead-scores': TaskRecalculateLeadScores;
      'dispatch-sequences': TaskDispatchSequences;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Identificador estable; no cambiar después de crear datos
   */
  slug: string;
  /**
   * UUID de la organización en la instancia hosted de OpenBSP
   */
  openbspOrganizationId?: string | null;
  /**
   * organization_address para enviar mensajes (Meta phone_number_id)
   */
  openbspPhoneNumberId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * admin gestiona todo · agente opera CRM · viewer solo lectura
   */
  roles: ('admin' | 'agente' | 'viewer')[];
  active?: boolean | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  taxId?: string | null;
  website?: string | null;
  email?: string | null;
  /**
   * Formato internacional sin +: ej 584121234567
   */
  phone?: string | null;
  city?: string | null;
  state?: string | null;
  address?: string | null;
  googleMapsUrl?: string | null;
  socialHandle?: string | null;
  segment?: (number | null) | Segment;
  assignedAgent?: (number | null) | User;
  commercialNotes?: string | null;
  notes?: string | null;
  clients?: {
    docs?: (number | Client)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segments".
 */
export interface Segment {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  companyName?: string | null;
  taxId?: string | null;
  stage: 'nuevo' | 'activo' | 'inactivo' | 'perdido';
  email?: string | null;
  /**
   * Formato internacional sin +: ej 584121234567
   */
  phone?: string | null;
  city?: string | null;
  state?: string | null;
  address?: string | null;
  googleMapsUrl?: string | null;
  socialHandle?: string | null;
  segment?: (number | null) | Segment;
  /**
   * Cuenta a la que pertenece el contacto; una empresa puede tener varios contactos
   */
  company?: (number | null) | Company;
  lastContactChannel?: ('whatsapp' | 'instagram_dm' | 'llamada' | 'en_persona' | 'email' | 'otro') | null;
  lastContactedAt?: string | null;
  assignedAgent?: (number | null) | User;
  /**
   * Notas de reuniones, requerimientos específicos, acuerdos y feedback del cliente.
   */
  commercialNotes?: string | null;
  consent?: boolean | null;
  /**
   * Si tiene fecha, no se le debe contactar
   */
  optOutAt?: string | null;
  notes?: string | null;
  activities?: {
    docs?: (number | Activity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  conversations?: {
    docs?: (number | Conversation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  tasks?: {
    docs?: (number | Task)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  payments?: {
    docs?: (number | Payment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  memberships?: {
    docs?: (number | Membership)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  documents?: {
    docs?: (number | Document)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  formSubmissions?: {
    docs?: (number | FormSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  emailLog?: {
    docs?: (number | EmailLog)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  emailMessages?: {
    docs?: (number | EmailMessage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  appointments?: {
    docs?: (number | Appointment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  tenant?: (number | null) | Tenant;
  type: 'nota' | 'llamada' | 'whatsapp' | 'email' | 'reunion' | 'otro';
  occurredAt: string;
  summary: string;
  client?: (number | null) | Client;
  lead?: (number | null) | Lead;
  performedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  tenant?: (number | null) | Tenant;
  fullName: string;
  companyName?: string | null;
  position?: string | null;
  status: 'nuevo' | 'contactado' | 'calificado' | 'descartado';
  source:
    | 'manual'
    | 'google_maps'
    | 'puerta_fria'
    | 'llamada_fria'
    | 'whatsapp'
    | 'instagram_dm'
    | 'linkedin'
    | 'tally'
    | 'apify'
    | 'referido';
  phone?: string | null;
  email?: string | null;
  city?: string | null;
  state?: string | null;
  address?: string | null;
  /**
   * URL de la ficha del negocio en Google Maps
   */
  googleMapsUrl?: string | null;
  socialHandle?: string | null;
  website?: string | null;
  /**
   * Link directo wa.me/... del contacto
   */
  whatsappLink?: string | null;
  segment?: (number | null) | Segment;
  /**
   * Cuenta del prospecto, si aplica; se hereda al convertir a cliente
   */
  company?: (number | null) | Company;
  /**
   * Estimación de la oportunidad; alimenta el pipeline del workspace
   */
  estimatedValue?: number | null;
  nivelInteres?: ('frio' | 'templado' | 'caliente') | null;
  prioridad?: ('baja' | 'media' | 'alta') | null;
  servicioInteres?: string | null;
  personaInteres?: string | null;
  /**
   * ID de origen (p. ej. Fibery / CRM anterior) para trazabilidad de migración
   */
  identificador?: string | null;
  /**
   * Sector original del export de Fibery
   */
  sectorFibery?: string | null;
  lastContactChannel?: ('whatsapp' | 'instagram_dm' | 'llamada' | 'en_persona' | 'email' | 'otro') | null;
  lastContactedAt?: string | null;
  numeroDeLlamadas?: number | null;
  fechaProximaLlamada?: string | null;
  visitadoPresencialmente?: boolean | null;
  pudoHablarDecisor?: boolean | null;
  notasLlamada?: string | null;
  assignedTo?: (number | null) | User;
  /**
   * Notas de reuniones, objeciones expresadas, acuerdos verbales y contexto comercial clave.
   */
  commercialNotes?: string | null;
  notes?: string | null;
  /**
   * Se llena automáticamente al convertir el lead
   */
  convertedClient?: (number | null) | Client;
  /**
   * Instante de la conversión — habilita deltas de conversión por ventana real
   */
  convertedAt?: string | null;
  touchpoints?: {
    docs?: (number | Activity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  contenidoRelacionado?: {
    docs?: (number | Note)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  tareas?: {
    docs?: (number | Task)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  conversations?: {
    docs?: (number | Conversation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  tasks?: {
    docs?: (number | Task)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  formSubmissions?: {
    docs?: (number | FormSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  appointments?: {
    docs?: (number | Appointment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  kanbanStatus?: ('nuevo' | 'contactado' | 'calificado' | 'descartado') | null;
  kanbanOrderRank?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Notas enriquecidas del equipo (editor de texto rico, independientes o por cliente/lead).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('general' | 'cliente' | 'reunion' | 'seguimiento' | 'idea' | 'recordatorio') | null;
  /**
   * Las notas fijadas aparecen primero en /workspace/notes
   */
  pinned?: boolean | null;
  /**
   * Opcional: vincula la nota a un cliente del CRM
   */
  client?: (number | null) | Client;
  /**
   * Opcional: vincula la nota a un lead del pipeline
   */
  lead?: (number | null) | Lead;
  /**
   * Se rellena automáticamente con el usuario autenticado
   */
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  description?: string | null;
  status: 'pendiente' | 'en_progreso' | 'completada' | 'bloqueada' | 'cancelada';
  priority: 'baja' | 'media' | 'alta' | 'urgente';
  dueDate?: string | null;
  assignedTo?: (number | null) | User;
  client?: (number | null) | Client;
  lead?: (number | null) | Lead;
  source?:
    ('manual' | 'tally_complaint' | 'payment_overdue' | 'openbsp_error' | 'hermes_ai' | 'lead_hot' | 'sequence') | null;
  /**
   * Id de la inscripción: clave de idempotencia del paso (con sequenceStepIndex).
   */
  sequenceEnrollmentId?: number | null;
  sequenceStepIndex?: number | null;
  checklist?:
    | {
        item: string;
        done?: boolean | null;
        id?: string | null;
      }[]
    | null;
  completedAt?: string | null;
  kanbanStatus?: ('pendiente' | 'en_progreso' | 'completada' | 'bloqueada' | 'cancelada') | null;
  kanbanOrderRank?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  tenant?: (number | null) | Tenant;
  status?: ('open' | 'pending' | 'resolved') | null;
  priority?: ('baja' | 'media' | 'alta') | null;
  assignee?: (number | null) | User;
  /**
   * Mientras snooze activo, la conversación no aparece en abiertas
   */
  snoozeUntil?: string | null;
  labels?: ('seguimiento' | 'facturacion' | 'soporte' | 'renovacion' | 'urgente' | 'oportunidad')[] | null;
  channel: 'whatsapp' | 'instagram_dm' | 'whatsapp_web';
  /**
   * UUID de la conversación en OpenBSP; lo rellena el webhook
   */
  openbspId?: string | null;
  organizationAddress?: string | null;
  contactAddress: string;
  client?: (number | null) | Client;
  lead?: (number | null) | Lead;
  lastMessageAt?: string | null;
  /**
   * Si es mayor a 24h, solo se pueden enviar plantillas
   */
  lastInboundAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  tenant?: (number | null) | Tenant;
  formName: string;
  /**
   * Tally form_id o ID de la plataforma
   */
  formId?: string | null;
  /**
   * eventId/responseId del webhook: si ya existe, la reentrega se ignora
   */
  eventId?: string | null;
  source: 'tally' | 'typeform' | 'web' | 'otro';
  respondentName?: string | null;
  respondentEmail?: string | null;
  respondentPhone?: string | null;
  client?: (number | null) | Client;
  lead?: (number | null) | Lead;
  /**
   * Marcado si la respuesta contiene queja o bajo NPS
   */
  isComplaint?: boolean | null;
  answersJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Citas espejadas de Google Calendar. Solo lectura: las escribe el job sync-gcal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  start: string;
  endDate?: string | null;
  allDay?: boolean | null;
  status: 'confirmed' | 'tentative' | 'cancelled';
  location?: string | null;
  /**
   * Emails separados por comas
   */
  attendees?: string | null;
  description?: string | null;
  /**
   * Idempotencia: reintentos del sync no duplican
   */
  gcalEventId: string;
  calendarId?: string | null;
  /**
   * Link directo a Google Calendar
   */
  htmlLink?: string | null;
  /**
   * Lo rellena el sync por matching de asistentes contra clients/leads
   */
  client?: (number | null) | Client;
  /**
   * Lo rellena el sync por matching de asistentes contra clients/leads
   */
  lead?: (number | null) | Lead;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  tenant?: (number | null) | Tenant;
  client: number | Client;
  amount: number;
  /**
   * Ej: Mensualidad web julio, Mantenimiento CRM
   */
  concept?: string | null;
  dueDate: string;
  status: 'pendiente' | 'pagado' | 'vencido' | 'anulado';
  method?: ('pago_movil' | 'transferencia' | 'zelle' | 'binance' | 'efectivo' | 'otro') | null;
  paidAt?: string | null;
  /**
   * Lo actualiza el job payment-reminders
   */
  reminderSentAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  tenant?: (number | null) | Tenant;
  client: number | Client;
  /**
   * Ej: Web básica, CRM + Redes, Mantenimiento premium
   */
  plan: string;
  monthlyPrice: number;
  status: 'activa' | 'pausada' | 'vencida' | 'cancelada';
  startDate: string;
  renewalDate: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  client: number | Client;
  documentType: 'contrato' | 'factura' | 'otro';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Registro de emails enviados. Lo escribe el sistema; los eventos de Resend actualizan el estado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log".
 */
export interface EmailLog {
  id: number;
  tenant?: (number | null) | Tenant;
  to: string;
  from?: string | null;
  subject: string;
  /**
   * queued→sent lo setea el envío; delivered/bounced/complained llegan por webhook de Resend
   */
  status: 'queued' | 'sent' | 'delivered' | 'bounced' | 'complained' | 'failed';
  source: 'transactional' | 'campaign' | 'sequence' | 'test';
  /**
   * email_id que devuelve la API; lo usa el webhook para actualizar el estado
   */
  providerMessageId?: string | null;
  campaign?: (number | null) | EmailCampaign;
  /**
   * Lo rellena el sistema al enviar, por matching del destinatario
   */
  client?: (number | null) | Client;
  /**
   * Lo rellena el sistema al enviar, por matching del destinatario
   */
  lead?: (number | null) | Lead;
  error?: string | null;
  /**
   * Id de la inscripción: clave de idempotencia del paso (con sequenceStepIndex).
   */
  sequenceEnrollmentId?: number | null;
  sequenceStepIndex?: number | null;
  eventsJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns".
 */
export interface EmailCampaign {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  subject: string;
  /**
   * Texto de vista previa en el inbox del destinatario
   */
  preheader?: string | null;
  /**
   * HTML del cuerpo. Se envuelve automáticamente con la plantilla base de la marca.
   */
  bodyHtml: string;
  /**
   * Destinatarios = leads + clientes de ese rubro con email válido
   */
  segment?: (number | null) | Segment;
  status: 'draft' | 'sending' | 'sent' | 'partial' | 'failed';
  /**
   * Fecha objetivo de envío. En v1 el despacho se activa desde la acción Enviar Campaña.
   */
  scheduledAt?: string | null;
  sentAt?: string | null;
  sentCount?: number | null;
  bouncedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Espejo del buzón sincronizado de Gmail. Solo lectura: lo escribe el job sync-email.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-messages".
 */
export interface EmailMessage {
  id: number;
  tenant?: (number | null) | Tenant;
  direction: 'inbound' | 'outbound';
  /**
   * Idempotencia: reintentos del sync no duplican
   */
  providerId: string;
  threadId?: string | null;
  fromEmail?: string | null;
  fromName?: string | null;
  /**
   * Lista separada por comas
   */
  toEmails?: string | null;
  /**
   * Lista separada por comas
   */
  ccEmails?: string | null;
  subject?: string | null;
  snippet?: string | null;
  date: string;
  /**
   * Lo rellena el sync por matching del email contra clients/leads
   */
  client?: (number | null) | Client;
  /**
   * Lo rellena el sync por matching del email contra clients/leads
   */
  lead?: (number | null) | Lead;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * PDFs generados por facturas y cotizaciones. Uso interno.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-media".
 */
export interface InvoiceMedia {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  tenant?: (number | null) | Tenant;
  conversation: number | Conversation;
  direction: 'inbound' | 'outbound';
  openbspId?: string | null;
  /**
   * Idempotencia: reintentos del webhook no duplican
   */
  externalId?: string | null;
  type:
    'text' | 'image' | 'video' | 'audio' | 'document' | 'sticker' | 'template' | 'location' | 'contacts' | 'unknown';
  text?: string | null;
  /**
   * Fidelidad total del objeto content recibido/enviado
   */
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Clave de claim de despacho (única por conversación). Oculta: uso interno.
   */
  idempotencyKey?: string | null;
  /**
   * {accepted, sent, delivered, read, failed, errors[]}
   */
  statusJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  senderAddress?: string | null;
  performedBy?: (number | null) | User;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-templates".
 */
export interface MessageTemplate {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Ej: recordatorio_pago — debe existir aprobado en Meta
   */
  name: string;
  language: string;
  category?: ('MARKETING' | 'UTILITY' | 'AUTHENTICATION') | null;
  metaStatus?: ('PENDING' | 'APPROVED' | 'REJECTED' | 'PAUSED' | 'DISABLED') | null;
  /**
   * Con placeholders {{1}}, {{2}}…
   */
  bodyText?: string | null;
  componentsJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  openbspTemplateId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  body?: string | null;
  severity: 'info' | 'warning' | 'error';
  /**
   * openbsp / jobs / formularios…
   */
  source?: string | null;
  /**
   * Momento real del incidente según la fuente (p. ej. created_at del log de OpenBSP). Vacío = momento de creación de la notificación.
   */
  occurredAt?: string | null;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catálogo de productos/servicios: alimenta cotizaciones y facturas
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Precio base sin impuestos; el IVA se aplica al cotizar/facturar
   */
  price: number;
  description?: string | null;
  /**
   * Para qué tipo de cliente aplica este offer
   */
  segment?: (number | null) | Segment;
  /**
   * Los inactivos no se ofrecen en nuevas cotizaciones
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pizarras colaborativas del tenant (Excalidraw). Compartidas por todos los agentes del workspace.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboards".
 */
export interface Whiteboard {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Escena Excalidraw: { elements: [...], files: {...} }. Guardada por el editor, no editar a mano.
   */
  scene:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Vista previa PNG (dataURL) generada en el cliente. Informativa, no se valida como imagen.
   */
  thumbnail?: string | null;
  source?: ('local' | 'import') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-briefs".
 */
export interface LeadBrief {
  id: number;
  tenant?: (number | null) | Tenant;
  lead: number | Lead;
  /**
   * Quién es, qué quiere y por dónde va la conversación.
   */
  summary?: string | null;
  /**
   * Una por línea: interés, objeciones, urgencia, cobros pendientes, etc.
   */
  senales?: string | null;
  sentiment?: ('positivo' | 'neutral' | 'negativo') | null;
  proximaAccion?: string | null;
  /**
   * Mensaje pre-escrito y personalizado para retomar el contacto.
   */
  mensajeWhatsapp?: string | null;
  /**
   * Proveedor/modelo que generó el brief (trazabilidad).
   */
  model?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversation-summaries".
 */
export interface ConversationSummary {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  conversation?: (number | null) | Conversation;
  client?: (number | null) | Client;
  lead?: (number | null) | Lead;
  summary: string;
  sentiment: 'positivo' | 'neutral' | 'negativo' | 'en_riesgo';
  /**
   * Precio, tiempos de entrega, dudas técnicas, etc.
   */
  objections?: string | null;
  nextSteps?: string | null;
  budgetExpectation?: string | null;
  keyTopics?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  generatedBy?: ('hermes_ai' | 'openbsp_agent' | 'manual') | null;
  rawAiResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Notas internas del equipo sobre conversaciones (privadas, no se envían al contacto).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversation-notes".
 */
export interface ConversationNote {
  id: number;
  tenant?: (number | null) | Tenant;
  conversation: number | Conversation;
  body: string;
  /**
   * Se rellena automáticamente con el usuario autenticado
   */
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Filtros guardados del CRM, privados por usuario.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-crm-views".
 */
export interface SavedCrmView {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  createdBy: number | User;
  vista: 'leads' | 'clientes' | 'empresas';
  modo?: ('pipeline' | 'tabla') | null;
  q?: string | null;
  /**
   * estado de lead o etapa de cliente según la vista; vacío = todos.
   */
  estado?: string | null;
  fuente?: string | null;
  /**
   * 'me', 'todos' o id numérico de usuario.
   */
  agente?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cadenas de nurturing por email para leads (pasos: email, tarea, esperar N días).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sequences".
 */
export interface Sequence {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Para qué sirve esta secuencia (ej: seguimiento post-cotización).
   */
  description?: string | null;
  /**
   * Las inscripciones de secuencias inactivas quedan en pausa (no se cancelan).
   */
  active?: boolean | null;
  /**
   * Con inscripciones activas no se puede cambiar la estructura (agregar/quitar/reordenar pasos); el contenido de cada paso sí es editable.
   */
  steps: {
    type: 'email' | 'tarea' | 'esperar';
    /**
     * Soporta {{nombre}} para personalizar con el nombre del lead.
     */
    subject?: string | null;
    /**
     * Se envuelve con la plantilla de marca. Soporta {{nombre}}. El HTML se sanitiza al guardar (sin scripts, iframes, handlers ni javascript:) — mismo modelo que las campañas.
     */
    bodyHtml?: string | null;
    taskTitle?: string | null;
    taskDueInDays?: number | null;
    days?: number | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Lo escribe el sistema y las acciones de inscripción; lectura en admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sequence-enrollments".
 */
export interface SequenceEnrollment {
  id: number;
  tenant?: (number | null) | Tenant;
  sequence: number | Sequence;
  lead: number | Lead;
  status: 'activa' | 'completada' | 'cancelada' | 'respondida';
  /**
   * Índice del próximo paso a procesar.
   */
  currentStep?: number | null;
  nextRunAt: string;
  /**
   * Fallos consecutivos del paso actual (un email fallido se reintenta hasta 3 veces).
   */
  stepAttempts?: number | null;
  enrolledBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-accounts".
 */
export interface SocialAccount {
  id: number;
  tenant?: (number | null) | Tenant;
  accountName: string;
  platform: 'instagram' | 'facebook';
  /**
   * Page ID, Instagram Business Account ID, o el identificador equivalente en tu gestor de redes (p. ej. Metricool)
   */
  platformAccountId: string;
  status: 'conectada' | 'desconectada' | 'expirada';
  profilePictureUrl?: string | null;
  /**
   * Referencia a la conexión del tenant en Composio — los tokens viven allá, nunca aquí.
   */
  composioConnectedAccountId?: string | null;
  externalUserId?: string | null;
  syncStatus?: ('sin_conectar' | 'ok' | 'error_token' | 'error_api') | null;
  lastSyncAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: number;
  tenant?: (number | null) | Tenant;
  caption: string;
  account: number | SocialAccount;
  media?: (number | Media)[] | null;
  status: 'borrador' | 'programado' | 'publicado' | 'fallido';
  scheduledAt?: string | null;
  publishedAt?: string | null;
  platformPostId?: string | null;
  permalink?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-metrics".
 */
export interface PostMetric {
  id: number;
  tenant?: (number | null) | Tenant;
  post: number | SocialPost;
  recordedAt: string;
  impressions?: number | null;
  reach?: number | null;
  likes?: number | null;
  comments?: number | null;
  shares?: number | null;
  saved?: number | null;
  rawMetrics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings".
 */
export interface CompanySetting {
  id: number;
  tenant?: (number | null) | Tenant;
  companyName: string;
  /**
   * Aplica a crons, calendario editorial y digestios (UTC-4)
   */
  timezone: string;
  currency: 'USD';
  digestHour: number;
  internalNotificationsEmail?: string | null;
  /**
   * Motor de inferencia para resúmenes de chat y análisis en segundo plano
   */
  aiProvider?: ('groq' | 'openrouter' | 'custom') | null;
  /**
   * Clave de Groq u OpenRouter. Si se deja vacía, se usará la variable de entorno GROQ_API_KEY / OPENROUTER_API_KEY.
   */
  aiApiKey?: string | null;
  /**
   * Ej: llama-3.3-70b-versatile (Groq), meta-llama/llama-3.3-70b-instruct (OpenRouter)
   */
  aiModel?: string | null;
  /**
   * Analizar automáticamente las conversaciones de WhatsApp cuando se detecte inactividad tras una ráfaga de mensajes
   */
  aiAutoSummarize?: boolean | null;
  /**
   * Se insertan automáticamente en cotizaciones, facturas y mensajes de cobranza por WhatsApp.
   */
  paymentMethods?: {
    pagoMovil?: {
      banco?: string | null;
      cedula?: string | null;
      telefono?: string | null;
    };
    transferenciaVes?: {
      banco?: string | null;
      numeroCuenta?: string | null;
      titular?: string | null;
      rif?: string | null;
    };
    zelle?: {
      email?: string | null;
      titular?: string | null;
    };
    binance?: {
      binanceId?: string | null;
      walletUsdt?: string | null;
    };
    swift?: {
      banco?: string | null;
      swift?: string | null;
      accountNumber?: string | null;
      titular?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * API key del proyecto Composio del tenant (cifrada). El superadmin la asigna desde /admin; el estado por servicio vive en Conexiones del Tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-integrations".
 */
export interface TenantIntegration {
  id: number;
  tenant?: (number | null) | Tenant;
  provider: 'composio';
  /**
   * Write-only: pegar la key del proyecto Composio del tenant. Al guardar se cifra y no vuelve a mostrarse.
   */
  apiKey?: string | null;
  apiKeyCifrado: string;
  estado: 'ok' | 'invalida';
  updatedAt: string;
  createdAt: string;
}
/**
 * Conexiones por servicio (login del tenant vía Composio), de la empresa o personales.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-connections".
 */
export interface TenantConnection {
  id: number;
  tenant?: (number | null) | Tenant;
  toolkit: 'instagram' | 'tiktok' | 'gmail' | 'googlecalendar' | 'googlesheets' | 'googledocs';
  scope: 'empresa' | 'personal';
  /**
   * Dueño de la cuenta personal. Vacío en conexiones de la empresa.
   */
  user?: (number | null) | User;
  /**
   * Auth config gestionado de Composio para este toolkit.
   */
  authConfigId?: string | null;
  connectedAccountId?: string | null;
  connectedBy?: (number | null) | User;
  estado: 'conectando' | 'ok' | 'error_token' | 'error_api' | 'desconectado';
  /**
   * Error crudo de Composio — sin fallback, se muestra en la UI.
   */
  ultimoError?: string | null;
  /**
   * Ej.: { "calendarId": "…", "mailbox": "…" } según el toolkit.
   */
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastSyncAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  tenant?: (number | null) | Tenant;
  issueDate?: string | null;
  dueDate?: string | null;
  client: {
    /**
     * Select a customer to auto-fill client details
     */
    customer?: (number | null) | Client;
    name: string;
    email?: string | null;
    address?: {
      street?: string | null;
      city?: string | null;
      postalCode?: string | null;
      country?: string | null;
    };
    vatNumber?: string | null;
  };
  items?:
    | {
        /**
         * Select a product to auto-fill description and price
         */
        product?: (number | null) | Offer;
        /**
         * Auto-filled when a product is selected. Changing the product overrides this value.
         */
        description: string;
        quantity: number;
        /**
         * Auto-filled when a product is selected. Changing the product overrides this value.
         */
        unitPrice: number;
        taxRate?: number | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  subtotal?: number | null;
  taxTotal?: number | null;
  total?: number | null;
  generatedPdfs?: (number | InvoiceMedia)[] | null;
  lastSentAt?: string | null;
  sendHistory?:
    | {
        sentAt?: string | null;
        to?: string | null;
        templateUsed?: string | null;
        subject?: string | null;
        attachedPdf?: (number | null) | InvoiceMedia;
        sentBy?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  invoiceNumber?: string | null;
  status?: ('draft' | 'sent' | 'paid' | 'overdue' | 'cancelled') | null;
  template?: ('Classic' | 'Modern' | 'Minimal' | 'Bold') | null;
  sourceQuote?: (number | null) | Quote;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  tenant?: (number | null) | Tenant;
  issueDate?: string | null;
  validUntil?: string | null;
  client: {
    /**
     * Select a customer to auto-fill client details
     */
    customer?: (number | null) | Client;
    name: string;
    email?: string | null;
    address?: {
      street?: string | null;
      city?: string | null;
      postalCode?: string | null;
      country?: string | null;
    };
    vatNumber?: string | null;
  };
  items?:
    | {
        /**
         * Select a product to auto-fill description and price
         */
        product?: (number | null) | Offer;
        /**
         * Auto-filled when a product is selected. Changing the product overrides this value.
         */
        description: string;
        quantity: number;
        /**
         * Auto-filled when a product is selected. Changing the product overrides this value.
         */
        unitPrice: number;
        taxRate?: number | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  subtotal?: number | null;
  taxTotal?: number | null;
  total?: number | null;
  acceptToken?: string | null;
  rejectToken?: string | null;
  tokenExpiresAt?: string | null;
  rejectionReason?: string | null;
  generatedPdfs?: (number | InvoiceMedia)[] | null;
  lastSentAt?: string | null;
  sendHistory?:
    | {
        sentAt?: string | null;
        to?: string | null;
        templateUsed?: string | null;
        subject?: string | null;
        attachedPdf?: (number | null) | InvoiceMedia;
        sentBy?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  quoteNumber?: string | null;
  status?: ('draft' | 'sent' | 'accepted' | 'rejected' | 'expired') | null;
  template?: ('Classic' | 'Modern' | 'Minimal' | 'Bold') | null;
  relatedInvoices?: (number | Invoice)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  clients?: {
    /**
     * Allow clients to find clients.
     */
    find?: boolean | null;
    /**
     * Allow clients to create clients.
     */
    create?: boolean | null;
    /**
     * Allow clients to update clients.
     */
    update?: boolean | null;
  };
  leads?: {
    /**
     * Allow clients to find leads.
     */
    find?: boolean | null;
    /**
     * Allow clients to create leads.
     */
    create?: boolean | null;
    /**
     * Allow clients to update leads.
     */
    update?: boolean | null;
  };
  tasks?: {
    /**
     * Allow clients to find tasks.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tasks.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tasks.
     */
    update?: boolean | null;
  };
  payments?: {
    /**
     * Allow clients to find payments.
     */
    find?: boolean | null;
  };
  invoices?: {
    /**
     * Allow clients to find invoices.
     */
    find?: boolean | null;
  };
  quotes?: {
    /**
     * Allow clients to find quotes.
     */
    find?: boolean | null;
  };
  conversationSummaries?: {
    /**
     * Allow clients to find conversation-summaries.
     */
    find?: boolean | null;
    /**
     * Allow clients to create conversation-summaries.
     */
    create?: boolean | null;
    /**
     * Allow clients to update conversation-summaries.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
  };
  socialAccounts?: {
    /**
     * Allow clients to find social-accounts.
     */
    find?: boolean | null;
  };
  companies?: {
    /**
     * Allow clients to find companies.
     */
    find?: boolean | null;
  };
  socialPosts?: {
    /**
     * Allow clients to find social-posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create social-posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update social-posts.
     */
    update?: boolean | null;
  };
  postMetrics?: {
    /**
     * Allow clients to find post-metrics.
     */
    find?: boolean | null;
    /**
     * Allow clients to create post-metrics.
     */
    create?: boolean | null;
    /**
     * Allow clients to update post-metrics.
     */
    update?: boolean | null;
  };
  users?: {
    /**
     * Allow clients to find users.
     */
    find?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'payment-reminders'
          | 'daily-digest'
          | 'sync-templates'
          | 'openbsp-error-poll'
          | 'send-campaign-batch'
          | 'send-scheduled-campaigns'
          | 'sync-email'
          | 'sync-gcal'
          | 'generate-lead-brief'
          | 'summarize-conversation'
          | 'sweep-unsummarized-conversations'
          | 'recalculate-lead-scores'
          | 'dispatch-sequences'
          | 'createCollectionExport'
          | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'payment-reminders'
        | 'daily-digest'
        | 'sync-templates'
        | 'openbsp-error-poll'
        | 'send-campaign-batch'
        | 'send-scheduled-campaigns'
        | 'sync-email'
        | 'sync-gcal'
        | 'generate-lead-brief'
        | 'summarize-conversation'
        | 'sweep-unsummarized-conversations'
        | 'recalculate-lead-scores'
        | 'dispatch-sequences'
        | 'createCollectionExport'
        | 'createCollectionImport'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'appointments';
        value: number | Appointment;
      } | null)
    | ({
        relationTo: 'segments';
        value: number | Segment;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'invoice-media';
        value: number | InvoiceMedia;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'message-templates';
        value: number | MessageTemplate;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'email-log';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'email-messages';
        value: number | EmailMessage;
      } | null)
    | ({
        relationTo: 'email-campaigns';
        value: number | EmailCampaign;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'whiteboards';
        value: number | Whiteboard;
      } | null)
    | ({
        relationTo: 'lead-briefs';
        value: number | LeadBrief;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'conversation-summaries';
        value: number | ConversationSummary;
      } | null)
    | ({
        relationTo: 'conversation-notes';
        value: number | ConversationNote;
      } | null)
    | ({
        relationTo: 'saved-crm-views';
        value: number | SavedCrmView;
      } | null)
    | ({
        relationTo: 'sequences';
        value: number | Sequence;
      } | null)
    | ({
        relationTo: 'sequence-enrollments';
        value: number | SequenceEnrollment;
      } | null)
    | ({
        relationTo: 'social-accounts';
        value: number | SocialAccount;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: number | SocialPost;
      } | null)
    | ({
        relationTo: 'post-metrics';
        value: number | PostMetric;
      } | null)
    | ({
        relationTo: 'company-settings';
        value: number | CompanySetting;
      } | null)
    | ({
        relationTo: 'tenant-integrations';
        value: number | TenantIntegration;
      } | null)
    | ({
        relationTo: 'tenant-connections';
        value: number | TenantConnection;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  openbspOrganizationId?: T;
  openbspPhoneNumberId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  active?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  taxId?: T;
  website?: T;
  email?: T;
  phone?: T;
  city?: T;
  state?: T;
  address?: T;
  googleMapsUrl?: T;
  socialHandle?: T;
  segment?: T;
  assignedAgent?: T;
  commercialNotes?: T;
  notes?: T;
  clients?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  companyName?: T;
  taxId?: T;
  stage?: T;
  email?: T;
  phone?: T;
  city?: T;
  state?: T;
  address?: T;
  googleMapsUrl?: T;
  socialHandle?: T;
  segment?: T;
  company?: T;
  lastContactChannel?: T;
  lastContactedAt?: T;
  assignedAgent?: T;
  commercialNotes?: T;
  consent?: T;
  optOutAt?: T;
  notes?: T;
  activities?: T;
  conversations?: T;
  tasks?: T;
  payments?: T;
  memberships?: T;
  documents?: T;
  formSubmissions?: T;
  emailLog?: T;
  emailMessages?: T;
  appointments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  tenant?: T;
  fullName?: T;
  companyName?: T;
  position?: T;
  status?: T;
  source?: T;
  phone?: T;
  email?: T;
  city?: T;
  state?: T;
  address?: T;
  googleMapsUrl?: T;
  socialHandle?: T;
  website?: T;
  whatsappLink?: T;
  segment?: T;
  company?: T;
  estimatedValue?: T;
  nivelInteres?: T;
  prioridad?: T;
  servicioInteres?: T;
  personaInteres?: T;
  identificador?: T;
  sectorFibery?: T;
  lastContactChannel?: T;
  lastContactedAt?: T;
  numeroDeLlamadas?: T;
  fechaProximaLlamada?: T;
  visitadoPresencialmente?: T;
  pudoHablarDecisor?: T;
  notasLlamada?: T;
  assignedTo?: T;
  commercialNotes?: T;
  notes?: T;
  convertedClient?: T;
  convertedAt?: T;
  touchpoints?: T;
  contenidoRelacionado?: T;
  tareas?: T;
  conversations?: T;
  tasks?: T;
  formSubmissions?: T;
  appointments?: T;
  kanbanStatus?: T;
  kanbanOrderRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  tenant?: T;
  type?: T;
  occurredAt?: T;
  summary?: T;
  client?: T;
  lead?: T;
  performedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  start?: T;
  endDate?: T;
  allDay?: T;
  status?: T;
  location?: T;
  attendees?: T;
  description?: T;
  gcalEventId?: T;
  calendarId?: T;
  htmlLink?: T;
  client?: T;
  lead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segments_select".
 */
export interface SegmentsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  client?: T;
  documentType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-media_select".
 */
export interface InvoiceMediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  tenant?: T;
  client?: T;
  amount?: T;
  concept?: T;
  dueDate?: T;
  status?: T;
  method?: T;
  paidAt?: T;
  reminderSentAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  tenant?: T;
  client?: T;
  plan?: T;
  monthlyPrice?: T;
  status?: T;
  startDate?: T;
  renewalDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  tenant?: T;
  status?: T;
  priority?: T;
  assignee?: T;
  snoozeUntil?: T;
  labels?: T;
  channel?: T;
  openbspId?: T;
  organizationAddress?: T;
  contactAddress?: T;
  client?: T;
  lead?: T;
  lastMessageAt?: T;
  lastInboundAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  tenant?: T;
  conversation?: T;
  direction?: T;
  openbspId?: T;
  externalId?: T;
  type?: T;
  text?: T;
  content?: T;
  idempotencyKey?: T;
  statusJson?: T;
  senderAddress?: T;
  performedBy?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-templates_select".
 */
export interface MessageTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  language?: T;
  category?: T;
  metaStatus?: T;
  bodyText?: T;
  componentsJson?: T;
  openbspTemplateId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  body?: T;
  severity?: T;
  source?: T;
  occurredAt?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log_select".
 */
export interface EmailLogSelect<T extends boolean = true> {
  tenant?: T;
  to?: T;
  from?: T;
  subject?: T;
  status?: T;
  source?: T;
  providerMessageId?: T;
  campaign?: T;
  client?: T;
  lead?: T;
  error?: T;
  sequenceEnrollmentId?: T;
  sequenceStepIndex?: T;
  eventsJson?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-messages_select".
 */
export interface EmailMessagesSelect<T extends boolean = true> {
  tenant?: T;
  direction?: T;
  providerId?: T;
  threadId?: T;
  fromEmail?: T;
  fromName?: T;
  toEmails?: T;
  ccEmails?: T;
  subject?: T;
  snippet?: T;
  date?: T;
  client?: T;
  lead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  subject?: T;
  preheader?: T;
  bodyHtml?: T;
  segment?: T;
  status?: T;
  scheduledAt?: T;
  sentAt?: T;
  sentCount?: T;
  bouncedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  price?: T;
  description?: T;
  segment?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  body?: T;
  category?: T;
  pinned?: T;
  client?: T;
  lead?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whiteboards_select".
 */
export interface WhiteboardsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  scene?: T;
  thumbnail?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-briefs_select".
 */
export interface LeadBriefsSelect<T extends boolean = true> {
  tenant?: T;
  lead?: T;
  summary?: T;
  senales?: T;
  sentiment?: T;
  proximaAccion?: T;
  mensajeWhatsapp?: T;
  model?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  formName?: T;
  formId?: T;
  eventId?: T;
  source?: T;
  respondentName?: T;
  respondentEmail?: T;
  respondentPhone?: T;
  client?: T;
  lead?: T;
  isComplaint?: T;
  answersJson?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  status?: T;
  priority?: T;
  dueDate?: T;
  assignedTo?: T;
  client?: T;
  lead?: T;
  source?: T;
  sequenceEnrollmentId?: T;
  sequenceStepIndex?: T;
  checklist?:
    | T
    | {
        item?: T;
        done?: T;
        id?: T;
      };
  completedAt?: T;
  kanbanStatus?: T;
  kanbanOrderRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversation-summaries_select".
 */
export interface ConversationSummariesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  conversation?: T;
  client?: T;
  lead?: T;
  summary?: T;
  sentiment?: T;
  objections?: T;
  nextSteps?: T;
  budgetExpectation?: T;
  keyTopics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  generatedBy?: T;
  rawAiResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversation-notes_select".
 */
export interface ConversationNotesSelect<T extends boolean = true> {
  tenant?: T;
  conversation?: T;
  body?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-crm-views_select".
 */
export interface SavedCrmViewsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  createdBy?: T;
  vista?: T;
  modo?: T;
  q?: T;
  estado?: T;
  fuente?: T;
  agente?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sequences_select".
 */
export interface SequencesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  active?: T;
  steps?:
    | T
    | {
        type?: T;
        subject?: T;
        bodyHtml?: T;
        taskTitle?: T;
        taskDueInDays?: T;
        days?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sequence-enrollments_select".
 */
export interface SequenceEnrollmentsSelect<T extends boolean = true> {
  tenant?: T;
  sequence?: T;
  lead?: T;
  status?: T;
  currentStep?: T;
  nextRunAt?: T;
  stepAttempts?: T;
  enrolledBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-accounts_select".
 */
export interface SocialAccountsSelect<T extends boolean = true> {
  tenant?: T;
  accountName?: T;
  platform?: T;
  platformAccountId?: T;
  status?: T;
  profilePictureUrl?: T;
  composioConnectedAccountId?: T;
  externalUserId?: T;
  syncStatus?: T;
  lastSyncAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  tenant?: T;
  caption?: T;
  account?: T;
  media?: T;
  status?: T;
  scheduledAt?: T;
  publishedAt?: T;
  platformPostId?: T;
  permalink?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-metrics_select".
 */
export interface PostMetricsSelect<T extends boolean = true> {
  tenant?: T;
  post?: T;
  recordedAt?: T;
  impressions?: T;
  reach?: T;
  likes?: T;
  comments?: T;
  shares?: T;
  saved?: T;
  rawMetrics?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings_select".
 */
export interface CompanySettingsSelect<T extends boolean = true> {
  tenant?: T;
  companyName?: T;
  timezone?: T;
  currency?: T;
  digestHour?: T;
  internalNotificationsEmail?: T;
  aiProvider?: T;
  aiApiKey?: T;
  aiModel?: T;
  aiAutoSummarize?: T;
  paymentMethods?:
    | T
    | {
        pagoMovil?:
          | T
          | {
              banco?: T;
              cedula?: T;
              telefono?: T;
            };
        transferenciaVes?:
          | T
          | {
              banco?: T;
              numeroCuenta?: T;
              titular?: T;
              rif?: T;
            };
        zelle?:
          | T
          | {
              email?: T;
              titular?: T;
            };
        binance?:
          | T
          | {
              binanceId?: T;
              walletUsdt?: T;
            };
        swift?:
          | T
          | {
              banco?: T;
              swift?: T;
              accountNumber?: T;
              titular?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-integrations_select".
 */
export interface TenantIntegrationsSelect<T extends boolean = true> {
  tenant?: T;
  provider?: T;
  apiKey?: T;
  apiKeyCifrado?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-connections_select".
 */
export interface TenantConnectionsSelect<T extends boolean = true> {
  tenant?: T;
  toolkit?: T;
  scope?: T;
  user?: T;
  authConfigId?: T;
  connectedAccountId?: T;
  connectedBy?: T;
  estado?: T;
  ultimoError?: T;
  config?: T;
  lastSyncAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  tenant?: T;
  issueDate?: T;
  dueDate?: T;
  client?:
    | T
    | {
        customer?: T;
        name?: T;
        email?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              postalCode?: T;
              country?: T;
            };
        vatNumber?: T;
      };
  items?:
    | T
    | {
        product?: T;
        description?: T;
        quantity?: T;
        unitPrice?: T;
        taxRate?: T;
        lineTotal?: T;
        id?: T;
      };
  notes?: T;
  subtotal?: T;
  taxTotal?: T;
  total?: T;
  generatedPdfs?: T;
  lastSentAt?: T;
  sendHistory?:
    | T
    | {
        sentAt?: T;
        to?: T;
        templateUsed?: T;
        subject?: T;
        attachedPdf?: T;
        sentBy?: T;
        id?: T;
      };
  invoiceNumber?: T;
  status?: T;
  template?: T;
  sourceQuote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  tenant?: T;
  issueDate?: T;
  validUntil?: T;
  client?:
    | T
    | {
        customer?: T;
        name?: T;
        email?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              postalCode?: T;
              country?: T;
            };
        vatNumber?: T;
      };
  items?:
    | T
    | {
        product?: T;
        description?: T;
        quantity?: T;
        unitPrice?: T;
        taxRate?: T;
        lineTotal?: T;
        id?: T;
      };
  notes?: T;
  subtotal?: T;
  taxTotal?: T;
  total?: T;
  acceptToken?: T;
  rejectToken?: T;
  tokenExpiresAt?: T;
  rejectionReason?: T;
  generatedPdfs?: T;
  lastSentAt?: T;
  sendHistory?:
    | T
    | {
        sentAt?: T;
        to?: T;
        templateUsed?: T;
        subject?: T;
        attachedPdf?: T;
        sentBy?: T;
        id?: T;
      };
  quoteNumber?: T;
  status?: T;
  template?: T;
  relatedInvoices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  clients?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  leads?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  tasks?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  payments?:
    | T
    | {
        find?: T;
      };
  invoices?:
    | T
    | {
        find?: T;
      };
  quotes?:
    | T
    | {
        find?: T;
      };
  conversationSummaries?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
      };
  socialAccounts?:
    | T
    | {
        find?: T;
      };
  companies?:
    | T
    | {
        find?: T;
      };
  socialPosts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  postMetrics?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  users?:
    | T
    | {
        find?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-info".
 */
export interface ShopInfo {
  id: number;
  companyName: string;
  companyLogo?: (number | null) | Media;
  address?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  vatNumber?: string | null;
  siret?: string | null;
  iban?: string | null;
  bic?: string | null;
  bankName?: string | null;
  legalMentions?: string | null;
  defaultPaymentTerms?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-info_select".
 */
export interface ShopInfoSelect<T extends boolean = true> {
  companyName?: T;
  companyLogo?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  phone?: T;
  email?: T;
  website?: T;
  vatNumber?: T;
  siret?: T;
  iban?: T;
  bic?: T;
  bankName?: T;
  legalMentions?: T;
  defaultPaymentTerms?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPayment-reminders".
 */
export interface TaskPaymentReminders {
  input?: unknown;
  output: {
    reminded?: number | null;
    markedOverdue?: number | null;
    skippedNoEmail?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDaily-digest".
 */
export interface TaskDailyDigest {
  input?: unknown;
  output: {
    sent?: boolean | null;
    summary?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSync-templates".
 */
export interface TaskSyncTemplates {
  input?: unknown;
  output: {
    synced?: number | null;
    skippedReason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskOpenbsp-error-poll".
 */
export interface TaskOpenbspErrorPoll {
  input?: unknown;
  output: {
    notified?: number | null;
    skippedReason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-campaign-batch".
 */
export interface TaskSendCampaignBatch {
  input: {
    campaignId: number;
    tenantId: number;
  };
  output: {
    sent?: number | null;
    failed?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-scheduled-campaigns".
 */
export interface TaskSendScheduledCampaigns {
  input?: unknown;
  output: {
    queued?: number | null;
    skipped?: number | null;
    summary?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSync-email".
 */
export interface TaskSyncEmail {
  input?: unknown;
  output: {
    synced?: number | null;
    skipped?: number | null;
    summary?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSync-gcal".
 */
export interface TaskSyncGcal {
  input?: unknown;
  output: {
    synced?: number | null;
    summary?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-lead-brief".
 */
export interface TaskGenerateLeadBrief {
  input: {
    leadId: number;
    tenantId: number;
  };
  output: {
    briefId?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSummarize-conversation".
 */
export interface TaskSummarizeConversation {
  input: {
    conversationId: number;
    tenantId: number;
    trigger?: string | null;
  };
  output: {
    summaryId?: number | null;
    skippedReason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSweep-unsummarized-conversations".
 */
export interface TaskSweepUnsummarizedConversations {
  input?: unknown;
  output: {
    queued?: number | null;
    skipped?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRecalculate-lead-scores".
 */
export interface TaskRecalculateLeadScores {
  input?: unknown;
  output: {
    scored?: number | null;
    updated?: number | null;
    promoted?: number | null;
    summary?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDispatch-sequences".
 */
export interface TaskDispatchSequences {
  input?: unknown;
  output: {
    processed?: number | null;
    emailsSent?: number | null;
    emailsFailed?: number | null;
    tasksCreated?: number | null;
    stopped?: number | null;
    completed?: number | null;
    summary?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'tenants'
      | 'users'
      | 'companies'
      | 'clients'
      | 'leads'
      | 'activities'
      | 'appointments'
      | 'segments'
      | 'documents'
      | 'media'
      | 'invoice-media'
      | 'payments'
      | 'memberships'
      | 'conversations'
      | 'messages'
      | 'message-templates'
      | 'notifications'
      | 'email-log'
      | 'email-messages'
      | 'email-campaigns'
      | 'offers'
      | 'notes'
      | 'whiteboards'
      | 'lead-briefs'
      | 'form-submissions'
      | 'tasks'
      | 'conversation-summaries'
      | 'conversation-notes'
      | 'saved-crm-views'
      | 'sequences'
      | 'sequence-enrollments'
      | 'social-accounts'
      | 'social-posts'
      | 'post-metrics'
      | 'company-settings'
      | 'tenant-integrations'
      | 'tenant-connections'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}