/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    clients: Client;
    leads: Lead;
    activities: Activity;
    segments: Segment;
    documents: Document;
    media: Media;
    payments: Payment;
    memberships: Membership;
    conversations: Conversation;
    messages: Message;
    'message-templates': MessageTemplate;
    notifications: Notification;
    'email-log': EmailLog;
    'email-campaigns': EmailCampaign;
    'company-settings': CompanySetting;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    clients: {
      activities: 'activities';
    };
  };
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    segments: SegmentsSelect<false> | SegmentsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'message-templates': MessageTemplatesSelect<false> | MessageTemplatesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'email-log': EmailLogSelect<false> | EmailLogSelect<true>;
    'email-campaigns': EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    'company-settings': CompanySettingsSelect<false> | CompanySettingsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'payment-reminders': TaskPaymentReminders;
      'daily-digest': TaskDailyDigest;
      'sync-templates': TaskSyncTemplates;
      'openbsp-error-poll': TaskOpenbspErrorPoll;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Identificador estable; no cambiar después de crear datos
   */
  slug: string;
  /**
   * UUID de la organización en la instancia hosted de OpenBSP
   */
  openbspOrganizationId?: string | null;
  /**
   * organization_address para enviar mensajes (Meta phone_number_id)
   */
  openbspPhoneNumberId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * admin gestiona todo · agente opera CRM · viewer solo lectura
   */
  roles: ('admin' | 'agente' | 'viewer')[];
  active?: boolean | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  stage: 'nuevo' | 'activo' | 'inactivo' | 'perdido';
  email?: string | null;
  /**
   * Formato internacional sin +: ej 584121234567
   */
  phone?: string | null;
  segment?: (number | null) | Segment;
  assignedAgent?: (number | null) | User;
  consent?: boolean | null;
  /**
   * Si tiene fecha, no se le debe contactar
   */
  optOutAt?: string | null;
  notes?: string | null;
  activities?: {
    docs?: (number | Activity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segments".
 */
export interface Segment {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  tenant?: (number | null) | Tenant;
  type: 'nota' | 'llamada' | 'whatsapp' | 'email' | 'reunion' | 'otro';
  occurredAt: string;
  summary: string;
  client?: (number | null) | Client;
  lead?: (number | null) | Lead;
  performedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  tenant?: (number | null) | Tenant;
  fullName: string;
  status: 'nuevo' | 'contactado' | 'calificado' | 'descartado';
  source: 'manual' | 'apify' | 'tally' | 'whatsapp' | 'instagram_dm' | 'referido';
  phone?: string | null;
  email?: string | null;
  segment?: (number | null) | Segment;
  notes?: string | null;
  /**
   * Se llena automáticamente al convertir el lead
   */
  convertedClient?: (number | null) | Client;
  kanbanStatus?: ('nuevo' | 'contactado' | 'calificado' | 'descartado') | null;
  kanbanOrderRank?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  client: number | Client;
  documentType: 'contrato' | 'factura' | 'otro';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  tenant?: (number | null) | Tenant;
  client: number | Client;
  amount: number;
  /**
   * Ej: Mensualidad web julio, Mantenimiento CRM
   */
  concept?: string | null;
  dueDate: string;
  status: 'pendiente' | 'pagado' | 'vencido' | 'anulado';
  method?: ('pago_movil' | 'transferencia' | 'zelle' | 'binance' | 'efectivo' | 'otro') | null;
  paidAt?: string | null;
  /**
   * Lo actualiza el job payment-reminders
   */
  reminderSentAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  tenant?: (number | null) | Tenant;
  client: number | Client;
  /**
   * Ej: Web básica, CRM + Redes, Mantenimiento premium
   */
  plan: string;
  monthlyPrice: number;
  status: 'activa' | 'pausada' | 'vencida' | 'cancelada';
  startDate: string;
  renewalDate: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  tenant?: (number | null) | Tenant;
  channel: 'whatsapp' | 'instagram_dm' | 'whatsapp_web';
  /**
   * UUID de la conversación en OpenBSP; lo rellena el webhook
   */
  openbspId?: string | null;
  organizationAddress?: string | null;
  contactAddress: string;
  client?: (number | null) | Client;
  lead?: (number | null) | Lead;
  lastMessageAt?: string | null;
  /**
   * Si es mayor a 24h, solo se pueden enviar plantillas
   */
  lastInboundAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  tenant?: (number | null) | Tenant;
  conversation: number | Conversation;
  direction: 'inbound' | 'outbound';
  openbspId?: string | null;
  /**
   * Idempotencia: reintentos del webhook no duplican
   */
  externalId?: string | null;
  type:
    'text' | 'image' | 'video' | 'audio' | 'document' | 'sticker' | 'template' | 'location' | 'contacts' | 'unknown';
  text?: string | null;
  /**
   * Fidelidad total del objeto content recibido/enviado
   */
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * {accepted, sent, delivered, read, failed, errors[]}
   */
  statusJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  senderAddress?: string | null;
  performedBy?: (number | null) | User;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-templates".
 */
export interface MessageTemplate {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Ej: recordatorio_pago — debe existir aprobado en Meta
   */
  name: string;
  language: string;
  category?: ('MARKETING' | 'UTILITY' | 'AUTHENTICATION') | null;
  metaStatus?: ('PENDING' | 'APPROVED' | 'REJECTED' | 'PAUSED' | 'DISABLED') | null;
  /**
   * Con placeholders {{1}}, {{2}}…
   */
  bodyText?: string | null;
  componentsJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  openbspTemplateId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  body?: string | null;
  severity: 'info' | 'warning' | 'error';
  /**
   * openbsp / jobs / formularios…
   */
  source?: string | null;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de emails enviados. Lo escribe el sistema; los eventos de Resend actualizan el estado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log".
 */
export interface EmailLog {
  id: number;
  tenant?: (number | null) | Tenant;
  to: string;
  from?: string | null;
  subject: string;
  /**
   * queued→sent lo setea el envío; delivered/bounced/complained llegan por webhook de Resend
   */
  status: 'queued' | 'sent' | 'delivered' | 'bounced' | 'complained' | 'failed';
  source: 'transactional' | 'campaign' | 'test';
  /**
   * email_id que devuelve la API; lo usa el webhook para actualizar el estado
   */
  providerMessageId?: string | null;
  campaign?: (number | null) | EmailCampaign;
  error?: string | null;
  eventsJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns".
 */
export interface EmailCampaign {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  subject: string;
  /**
   * Texto de vista previa en el inbox del destinatario
   */
  preheader?: string | null;
  /**
   * HTML del cuerpo. Se envuelve automáticamente con la plantilla base de la marca.
   */
  bodyHtml: string;
  /**
   * Destinatarios = leads + clientes de ese rubro con email válido
   */
  segment?: (number | null) | Segment;
  status: 'draft' | 'sending' | 'sent' | 'partial' | 'failed';
  /**
   * Informativo en v1: el envío es manual desde el botón Enviar
   */
  scheduledAt?: string | null;
  sentAt?: string | null;
  sentCount?: number | null;
  bouncedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings".
 */
export interface CompanySetting {
  id: number;
  tenant?: (number | null) | Tenant;
  companyName: string;
  /**
   * Aplica a crons, calendario editorial y digestios (UTC-4)
   */
  timezone: string;
  currency: 'USD';
  digestHour: number;
  internalNotificationsEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'payment-reminders'
          | 'daily-digest'
          | 'sync-templates'
          | 'openbsp-error-poll'
          | 'createCollectionExport'
          | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'payment-reminders'
        | 'daily-digest'
        | 'sync-templates'
        | 'openbsp-error-poll'
        | 'createCollectionExport'
        | 'createCollectionImport'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'segments';
        value: number | Segment;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'message-templates';
        value: number | MessageTemplate;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'email-log';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'email-campaigns';
        value: number | EmailCampaign;
      } | null)
    | ({
        relationTo: 'company-settings';
        value: number | CompanySetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  openbspOrganizationId?: T;
  openbspPhoneNumberId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  active?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  stage?: T;
  email?: T;
  phone?: T;
  segment?: T;
  assignedAgent?: T;
  consent?: T;
  optOutAt?: T;
  notes?: T;
  activities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  tenant?: T;
  fullName?: T;
  status?: T;
  source?: T;
  phone?: T;
  email?: T;
  segment?: T;
  notes?: T;
  convertedClient?: T;
  kanbanStatus?: T;
  kanbanOrderRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  tenant?: T;
  type?: T;
  occurredAt?: T;
  summary?: T;
  client?: T;
  lead?: T;
  performedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "segments_select".
 */
export interface SegmentsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  client?: T;
  documentType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  tenant?: T;
  client?: T;
  amount?: T;
  concept?: T;
  dueDate?: T;
  status?: T;
  method?: T;
  paidAt?: T;
  reminderSentAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  tenant?: T;
  client?: T;
  plan?: T;
  monthlyPrice?: T;
  status?: T;
  startDate?: T;
  renewalDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  tenant?: T;
  channel?: T;
  openbspId?: T;
  organizationAddress?: T;
  contactAddress?: T;
  client?: T;
  lead?: T;
  lastMessageAt?: T;
  lastInboundAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  tenant?: T;
  conversation?: T;
  direction?: T;
  openbspId?: T;
  externalId?: T;
  type?: T;
  text?: T;
  content?: T;
  statusJson?: T;
  senderAddress?: T;
  performedBy?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-templates_select".
 */
export interface MessageTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  language?: T;
  category?: T;
  metaStatus?: T;
  bodyText?: T;
  componentsJson?: T;
  openbspTemplateId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  body?: T;
  severity?: T;
  source?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log_select".
 */
export interface EmailLogSelect<T extends boolean = true> {
  tenant?: T;
  to?: T;
  from?: T;
  subject?: T;
  status?: T;
  source?: T;
  providerMessageId?: T;
  campaign?: T;
  error?: T;
  eventsJson?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  subject?: T;
  preheader?: T;
  bodyHtml?: T;
  segment?: T;
  status?: T;
  scheduledAt?: T;
  sentAt?: T;
  sentCount?: T;
  bouncedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings_select".
 */
export interface CompanySettingsSelect<T extends boolean = true> {
  tenant?: T;
  companyName?: T;
  timezone?: T;
  currency?: T;
  digestHour?: T;
  internalNotificationsEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPayment-reminders".
 */
export interface TaskPaymentReminders {
  input?: unknown;
  output: {
    reminded?: number | null;
    markedOverdue?: number | null;
    skippedNoEmail?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDaily-digest".
 */
export interface TaskDailyDigest {
  input?: unknown;
  output: {
    sent?: boolean | null;
    summary?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSync-templates".
 */
export interface TaskSyncTemplates {
  input?: unknown;
  output: {
    synced?: number | null;
    skippedReason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskOpenbsp-error-poll".
 */
export interface TaskOpenbspErrorPoll {
  input?: unknown;
  output: {
    notified?: number | null;
    skippedReason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'tenants'
      | 'users'
      | 'clients'
      | 'leads'
      | 'activities'
      | 'segments'
      | 'documents'
      | 'media'
      | 'payments'
      | 'memberships'
      | 'conversations'
      | 'messages'
      | 'message-templates'
      | 'notifications'
      | 'email-log'
      | 'email-campaigns'
      | 'company-settings'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}